/** Shared resume data for PDF templates */
export const resumeData = {
  personal: {
    name: 'Rajiul Islam',
    title: 'Front-End Developer',
  },
  contact: {
    phone: '+880 1986570093',
    email: 'developer.rajiul@gmail.com',
    linkedInUrl: 'https://www.linkedin.com/in/rajiul-islam-rayhan',
    linkedInLabel: 'LinkedIn Profile',
    portfolioUrl: 'https://rajiul-portfolio.vercel.app',
    portfolioLabel: 'Portfolio',
    location: 'Khulna, Bangladesh',
  },
  sectionLabels: {
    summary: 'SUMMARY',
    education: 'EDUCATION',
    experience: 'EXPERIENCE',
    additionalTraining: 'ADDITIONAL TRAINING',
    industrySkills: 'SKILLS',
    softSkills: 'SOFT SKILLS',
    personalProjects: 'PERSONAL PROJECTS',
    keyFeatures: 'Key Features:',
    liveDemo: 'Live',
    frontendGit: 'Frontend GitHub',
    backendGit: 'Backend GitHub',
    project: 'Project',
    languages: 'LANGUAGES',
    certifications: 'CERTIFICATIONS',
    bullet: '•',
  },
  summary:
    'Frontend Developer with 1+ year of experience building scalable web applications using React.js and Next.js. Skilled in TypeScript, Tailwind CSS, Tanstack Query, and state management (Redux/Zustand).',
  education: [
    {
      id: 1,
      degree: 'B.S.C EEE',
      institution: 'World University of Bangladesh',
      period: '2018 - 2022',
      location: 'Dhaka, Bangladesh',
    },
    {
      id: 2,
      degree: 'DIPLOMA IN ELECTRICAL',
      institution: 'Mangrove Institute of Science and Technology',
      period: '2013 - 2017',
      location: 'KHULNA, Bangladesh',
    },
  ],
  experience: {
    jobTitle: 'Junior Front-End Developer',
    company: 'Waditaslim tech',
    period: '2025 - Present',
    location: 'KHULNA, Bangladesh (Dubai Base)',
    projects: [
      {
        id: 1,
        title: 'Travel Booking Platform [OTA]',
        liveUrl: 'https://kingstartravel.com',
        description:
          'A multi-provider online travel booking platform built with React.js and Next.js, featuring role-based dashboards, multi-payment integration, and advanced admin management. ',
        responsibilities: [
          'Integrated Multi-OTA systems with separate UI inside a single application',
          'Built dynamic role-based user, agency, and admin dashboards',
          'Built accounts module with expense, invoice, supplier, and financial reports',
        ],
        tech: [
          'React.js',
          'Next.js',
          'TypeScript',
          'ShadCN UI',
          'zustand',
          'Tanstack Query',
          'Tanstack Table',
          'dayjs',
        ],
      },
      {
        id: 2,
        title: 'Multi-Tenant SaaS Platform',
        liveUrl: 'https://ezybuss.com/en',
        description:
          'A scalable multi-tenant SaaS platform that allows users to create and manage portfolio or eCommerce websites with dynamic templates, domain integration, and secure tenant-based architecture.',
        responsibilities: [
          'Built a central dashboard for template selection and dynamic content customization.',
          'Developed multi-language support with portfolio and eCommerce templates.',
          'Managed authentication, authorization, and tenant isolation using proper middleware',
        ],
        tech: [
          'React.js',
          'Next.js',
          'TypeScript',
          'ShadCN UI',
          'zustand',
          'Tanstack Query',
        ],
      },
    ],
  },
  additionalTraining: {
    title: 'Programming Hero – Online Web Development Course',
    description: 'Front End Web Development – Level 1 & Level 2 (Completed)',
  },
  technologies: [
    'Next.js',
    'TypeScript',
    'ShadCN UI',
    'Redux Toolkit',
    'Zustand',
    'Express JS',
    'Mongoose',
    'Node js',
    'Tanstack Query',
    'Git & GitHub',
    'figma',
    'Framer Motion',
    'dayjs',
  ],
  softSkills: [
    // {
    //   id: 1,
    //   icon: '/images/resume/book.png',
    //   title: 'Eager to Learn New Skills',
    //   description:
    //     'Continuously learning new technologies and best practices to improve code quality.',
    //   iconStyle: { width: 10, marginRight: 3 },
    // },
    // {
    //   id: 2,
    //   icon: '/images/resume/statistics.png',
    //   title: 'Not Afraid of Challenges',
    //   description:
    //     'Comfortable tackling complex problems and adapting to changing requirements.',
    //   iconStyle: { width: 10, marginRight: 3 },
    // },
    {
      id: 3,
      icon: '/images/resume/clock.png',
      title: 'Time Management',
      description:
        'Able to prioritize tasks and meet deadlines in fast-paced environments.',
      iconStyle: { width: 10, height: 10, marginRight: 3 },
    },
    {
      id: 4,
      icon: '/images/resume/group.png',
      title: 'Team Collaboration',
      description:
        'Works well in cross-functional teams and communicates clearly with stakeholders.',
      iconStyle: { width: 10, height: 10, marginRight: 3 },
    },
  ],
  personalProjects: [
    // {
    //   id: 1,
    //   title: 'E-Commerce Full Stack Application',
    //   duration: 'Jan 2024 - Mar 2024',
    //   description:
    //     'An e-commerce platform with product management, shopping cart, and payment integration.',
    //   features: [
    //     'User authentication and authorization',
    //     'Product catalog with search and filters',
    //     'Shopping cart and checkout process',
    //   ],
    //   liveLink: 'https://ecommerce-demo.vercel.app',
    //   frontendGit: 'https://github.com/username/ecommerce-frontend',
    //   backendGit: 'https://github.com/username/ecommerce-backend',
    //   tech: [
    //     'React.js',
    //     'Next.js',
    //     'TypeScript',
    //     'Tailwind CSS',
    //     'Redux Toolkit',
    //     'Stripe',
    //     'REST APIs',
    //   ],
    // },
    {
      id: 2,
      title: 'Services Marketplace',
      duration: 'Live Project',
      description:
        'A location-based service marketplace that connects users with nearby service providers for seamless discovery and engagement.',
      features: [
        'Location-Based Provider Discovery: Users can find nearby service providers based on their area, improving local relevance and booking intent.',
        'Category-Wise Service Listing: Services are organized by category so users can quickly filter providers by the exact service they need.',
        'Provider Profile Pages: Each provider has a dedicated profile with service details, coverage area, and contact-ready information.',
        'Search & Filter Experience: Supports fast searching and filtering to narrow results by service type and location context.',
        'Mobile-First UI: Optimized for mobile users who need quick access to local providers while on the go.',
        'Scalable Marketplace Architecture: Designed to onboard growing numbers of providers and categories without affecting browsing performance.',
      ],
      liveLink: 'https://www.service64.com/',
      frontendGit: 'https://github.com/example/ecommerce',
      backendGit: 'https://github.com/example/ecommerce',
      tech: [
        'Next.js',
        'React.js',
        'TypeScript',
        'Tailwind CSS',
        'Zustand',
        'TanStack Query',
        'React Hook Form',
        'Zod',
        'Axios',
        'JWT',
        'mongoose',
        'express',
      ],
    },
  ],
  languages: [
    { id: 1, name: 'Bengali', level: 'Native' },
    { id: 2, name: 'English', level: 'Fluent' },
  ],
  certifications: [
    {
      id: 1,
      name: 'Front End Web Development – Level 1 & 2',
      issuer: 'Programming Hero',
    },
    { id: 2, name: 'Responsive Web Design', issuer: 'freeCodeCamp' },
  ],
};
